{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "poolparty.fullname" . }}
  labels:
    {{- include "poolparty.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ include "poolparty.ingressHost" . | quote }}
      secretName: wildcard-tls
  rules:
    - host: {{ include "poolparty.ingressHost" . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "poolparty.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
