# Input variables for the Graphwise Stack AZURE module.
#
# Copy terraform.tfvars.example to terraform.tfvars, fill in the
# per-deployment values, and `terraform apply`. Defaults are the
# recommended shipping values -- only change them if you have a reason.
#
# === DO NOT EDIT THIS FILE for per-deployment values ======================
# Same rule as the AWS module: every per-deployment knob belongs in
# terraform.tfvars. Defaults here are a safety net, not a config surface.

# ---------------------------------------------------------------------------
# Azure subscription / placement
# ---------------------------------------------------------------------------

variable "subscription_id" {
  description = "Azure subscription ID (GUID) to deploy into. Required by the azurerm v4 provider. Leave empty to fall back to the ARM_SUBSCRIPTION_ID environment variable or the `az account set` default. Get it with: az account show --query id -o tsv"
  type        = string
  default     = ""

  validation {
    condition     = var.subscription_id == "" || can(regex("^[0-9a-fA-F-]{36}$", var.subscription_id))
    error_message = "subscription_id must be empty or a 36-character GUID (e.g. 00000000-1111-2222-3333-444444444444)."
  }
}

variable "location" {
  description = "Azure region to deploy into (e.g. \"westus2\", \"eastus\", \"westeurope\"). Pick one close to you for low SSH latency. IMPORTANT: the chosen region must offer the vm_size you pick -- memory-optimized E-series availability is regional. Verify BEFORE the first apply with: az vm list-skus --location <location> --size Standard_E8 --output table"
  type        = string
  default     = "westus2"
}

variable "resource_group_name" {
  description = "Name of the resource group Terraform CREATES to hold every resource in this deployment. `terraform destroy` deletes the group and everything in it, which is why the long-lived public IP should live in a DIFFERENT, operator-owned resource group (see existing_public_ip_resource_group_name). Leave empty to auto-name it \"<instance_name_prefix>-<subdomain-slug>-rg\"."
  type        = string
  default     = ""
}

# ---------------------------------------------------------------------------
# DNS + TLS (Route 53 stays on AWS -- see README.md "Why Route 53 stays")
# ---------------------------------------------------------------------------

variable "subdomain" {
  description = "Your subdomain path under base_domain. Single-level (\"scott\") or multi-level (\"demo.team\") both work. All app hostnames live one level deeper: poolparty.<subdomain>.<base_domain>, auth.<subdomain>.<base_domain>, graphrag.<subdomain>.<base_domain>, etc. You add two A records (<subdomain> + *.<subdomain>) in Route 53 pointing at the public IP."
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9]([a-z0-9.-]*[a-z0-9])?$", var.subdomain))
    error_message = "Subdomain must be lowercase, start/end with a letter or digit, and contain only letters, digits, dots, or hyphens. Multi-level (e.g. \"demo.team\") is supported."
  }
}

variable "base_domain" {
  description = "Parent domain that hosts the per-deployment subdomain. Must be a domain whose DNS is hosted in Route 53 -- the Azure stack still uses cert-manager's Route 53 DNS-01 solver for wildcard cert issuance, authenticated with the static IAM key pair below rather than an EC2 instance role. Nothing about the domain moves to Azure DNS. Required, deliberately with no default: a zone you do not control fails as AccessDenied partway through the deploy."
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9][a-z0-9.-]*[a-z0-9]$", var.base_domain))
    error_message = "Base domain must be lowercase, start/end with a letter or digit, and contain only letters, digits, dots, or hyphens."
  }
}

variable "route53_zone_id" {
  description = "Route 53 hosted zone ID for base_domain (e.g. \"Z01234567ABCDEFGHIJK\"). Get it once with: aws route53 list-hosted-zones --query 'HostedZones[?Name==`<base_domain>.`].Id' --output text | sed 's|/hostedzone/||'. Written to /etc/profile.d/graphwise.sh on the VM; scripts/cluster-bootstrap.sh feeds it to the cert-manager DNS-01 solver. NOTE: the AWS module's validation regex accepts any well-formed-but-WRONG zone ID; the same trap applies here (see CLAUDE.md -> 'Wrong route53_zone_id'). Verify the value, don't trust the regex."
  type        = string

  validation {
    condition     = can(regex("^Z[A-Z0-9]+$", var.route53_zone_id))
    error_message = "route53_zone_id must look like a Route 53 hosted zone ID, e.g. Z01234567ABCDEFGHIJK."
  }
}

variable "route53_credentials_file" {
  description = "Path to a local file holding the IAM access key pair that cert-manager uses for the Route 53 DNS-01 solver. Format is a plain shell env file with exactly these three lines: AWS_ACCESS_KEY_ID=..., AWS_SECRET_ACCESS_KEY=..., AWS_REGION=... . Default resolves to route53-credentials.env next to this module (gitignored by the folder-local .gitignore). This replaces the AWS module's EC2 instance role: an Azure VM has no way to assume an AWS role, so the credential has to be static. Scope the IAM user to route53:GetChange on change/* plus route53:ChangeResourceRecordSets + route53:ListResourceRecordSets on this ONE hosted zone ARN -- exactly the policy the AWS module's aws_iam_role_policy.ec2_route53 attaches. WARNING: the file's contents land in Terraform state; treat the state file as a secret."
  type        = string
  default     = ""
}

variable "le_email" {
  description = "Email address for the Let's Encrypt ACME account. LE rejects empty / malformed values AND rejects the RFC 2606 reserved domains (example.com / example.org / example.net). cloud-init writes it to /etc/profile.d/graphwise.sh so scripts/cluster-bootstrap.sh picks it up with no manual export."
  type        = string

  validation {
    condition     = can(regex("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$", var.le_email))
    error_message = "le_email must look like an email address (e.g. you@example.com)."
  }

  validation {
    condition     = !can(regex("@(example\\.(com|org|net))$", lower(var.le_email))) && !can(regex("CHANGEME", var.le_email))
    error_message = "le_email cannot use RFC 2606 reserved domains (@example.com / .org / .net) or the literal 'CHANGEME' placeholder -- Let's Encrypt rejects these with 'forbidden domain' at ACME account registration."
  }
}

# ---------------------------------------------------------------------------
# VM sizing + image
# ---------------------------------------------------------------------------

variable "vm_size" {
  description = "Azure VM size. Standard_E8s_v5 (8 vCPU / 64 GiB, x86_64) is the direct equivalent of the AWS module's r6g.2xlarge and the tested minimum: KIND control plane (~1.5 GB) + ingress-nginx + cert-manager + CNPG + Keycloak operator + Keycloak + 2 Postgres clusters + 2 GraphDB instances + Elasticsearch (8 GB heap) + PoolParty (8 GB heap) + 5 add-ons + 4 GraphRAG services adds up to ~50-55 GB working set. x86_64 is deliberate, not a fallback -- it lets the stack use the upstream ontotext/refine image directly instead of the bundled arm64 workaround (see README.md). Standard_E8ps_v5 is the ARM64 equivalent if you have a reason to want it; regional availability is patchier."
  type        = string
  default     = "Standard_E8s_v5"
}

variable "os_disk_gb" {
  description = "OS managed-disk size in GiB. 300 gives headroom for the KIND containerd image cache (every Helm chart pulls fresh into the node container), local-path-provisioner PVCs (GraphDB data, Postgres clusters, ES indices), and log growth. Can be grown later; can't be shrunk. NOTE: the AWS module's root_volume_gb defaults to 100 while its own description argues for 300 -- this module defaults to the recommended value instead of the inconsistent one."
  type        = number
  default     = 300
}

variable "os_disk_type" {
  description = "Managed-disk SKU for the OS disk. Premium_LRS is the equivalent of AWS gp3 for this workload -- KIND's containerd image cache and the Postgres/GraphDB/Elasticsearch PVCs all land on this one disk, so StandardSSD_LRS will feel slow during Helm installs. Premium_LRS requires an 's'-suffixed VM size (Standard_E8s_v5 qualifies)."
  type        = string
  default     = "Premium_LRS"
}

# --- Marketplace image (VERIFY BEFORE FIRST APPLY) --------------------------
# There is no Amazon Linux 2023 on Azure, so the distro decision reopens.
# These four fields default to Rocky Linux 9, which keeps the AWS module's
# `dnf` package flow almost verbatim.
#
# !! The exact publisher/offer/sku triple below is UNVERIFIED in this repo --
# !! nobody has run `az` against it yet. Confirm before your first apply:
# !!
# !!   az vm image list --publisher resf --all --output table
# !!   az vm image terms show --publisher resf --offer rockylinux-x86_64 --plan 9-base
# !!
# !! Rocky is a marketplace image and needs a ONE-TIME per-subscription terms
# !! acceptance (see README.md -> Prerequisites). If the triple is wrong, apply
# !! fails with an unhelpful "image not found"; these are variables precisely
# !! so you can correct them in terraform.tfvars without editing the module.

variable "image_publisher" {
  description = "Marketplace image publisher. Rocky Linux 9 = \"resf\". RHEL 9 = \"RedHat\". Ubuntu 24.04 = \"Canonical\". UNVERIFIED -- confirm with `az vm image list --publisher <p> --all -o table` before first apply."
  type        = string
  default     = "resf"
}

variable "image_offer" {
  description = "Marketplace image offer. Rocky Linux 9 = \"rockylinux-x86_64\". RHEL 9 = \"RHEL\". Ubuntu 24.04 = \"ubuntu-24_04-lts\". UNVERIFIED -- confirm with az before first apply. Changing the distro family also means editing user-data.sh.tpl (dnf vs apt) -- see README.md."
  type        = string
  default     = "rockylinux-x86_64"
}

variable "image_sku" {
  description = "Marketplace image SKU. Rocky Linux 9 = \"9-base\". RHEL 9 = \"9-lvm-gen2\". Ubuntu 24.04 = \"server\". UNVERIFIED -- confirm with az before first apply."
  type        = string
  default     = "9-base"
}

variable "image_version" {
  description = "Marketplace image version. \"latest\" is correct for the FIRST apply only. After a successful provision, run `terraform output -raw image_version_deployed` and pin this to the concrete version string -- the module also carries lifecycle.ignore_changes on source_image_reference, but pinning makes plan output honest. Same hazard as the AWS module's ami_override: an unpinned image that the publisher refreshes can mark the VM for replacement, destroying the OS disk and every PVC on it."
  type        = string
  default     = "latest"
}

variable "image_has_plan" {
  description = "Set true when the chosen marketplace image requires a purchase plan (most community/third-party images, including Rocky, do; first-party Canonical Ubuntu and RedHat RHEL PAYG generally do not). When true the module emits the `plan` block on the VM, which Azure requires alongside an accepted terms agreement. If apply fails with 'Creating a virtual machine from Marketplace image requires Plan information', flip this to true. If it fails with 'Plan information cannot be specified', flip it to false."
  type        = bool
  default     = true
}

# ---------------------------------------------------------------------------
# Access
# ---------------------------------------------------------------------------

variable "admin_username" {
  description = "Linux admin account created on the VM. Defaults to \"ec2-user\" ON PURPOSE, even though nothing about Azure is EC2. The repo hardcodes /home/ec2-user in files that have no templating path at all -- infra/kind/kind-config.yaml (extraMounts hostPath), charts/graphwise-stack/templates/staging-data.yaml, the graphwise-cluster-resume systemd unit, and the laptop ssh/scp helpers. Reusing the literal name makes every one of those files zero-edit and keeps the Azure and AWS paths byte-identical from the KIND layer up. Change it only if you are also prepared to introduce templating for kind-config.yaml."
  type        = string
  default     = "ec2-user"

  validation {
    # Azure rejects a fixed list of admin usernames (admin, administrator,
    # root, user, test, guest, ...). ec2-user is not on it, but a teammate
    # who overrides this should not discover the list at apply time.
    condition = !contains([
      "admin", "administrator", "root", "user", "user1", "user2", "user3",
      "user4", "user5", "test", "test1", "test2", "test3", "guest", "admin1",
      "console", "backup", "server", "support", "sys", "owner", "adm",
    ], lower(var.admin_username))
    error_message = "Azure rejects this username for Linux VM admin accounts. Pick another (the module default \"ec2-user\" is safe and is what the rest of the repo expects)."
  }
}

variable "ssh_public_key_path" {
  description = "Path to the SSH PUBLIC key (.pub) to install on the VM's admin account. Azure has no equivalent of an EC2 key pair -- you hand it the public key material directly and keep the private half locally, so there is no key_pair_name to pre-create in the portal. Point this at the .pub whose private key you will use for ssh/scp."
  type        = string
  default     = "~/.ssh/id_rsa.pub"
}

variable "admin_cidr" {
  description = "CIDR block allowed to reach the VM on ports 22, 80 and 443. Use your current public IP + /32 (check with `curl -4 icanhazip.com`). NEVER 0.0.0.0/0 -- this is the shell on a box that also hosts Keycloak. Let's Encrypt issuance and renewal are unaffected by locking 80/443 because the ClusterIssuer is DNS-01 via Route 53; no inbound port is required."
  type        = string

  validation {
    condition     = can(cidrhost(var.admin_cidr, 0))
    error_message = "admin_cidr must be a valid CIDR block (e.g. 203.0.113.42/32)."
  }

  validation {
    condition     = var.admin_cidr != "0.0.0.0/0"
    error_message = "admin_cidr must not be 0.0.0.0/0 -- that opens SSH and every app port to the entire internet."
  }
}

# ---------------------------------------------------------------------------
# Public IP (two modes, mirroring the AWS module's EIP handling)
# ---------------------------------------------------------------------------

variable "existing_public_ip_name" {
  description = "Name of a pre-created Static/Standard Public IP to attach to this VM. When set (together with existing_public_ip_resource_group_name), Terraform looks the IP up and only associates it -- it never manages the object, so `terraform destroy` leaves it intact and the Route 53 A records stay valid across rebuilds. This is the Azure twin of the AWS module's existing_eip_allocation_id, and it matters MORE here: destroy deletes the whole resource group, so a Terraform-managed IP is guaranteed to be lost. Create it once, in a SEPARATE long-lived resource group: az network public-ip create --name <name> --resource-group <long-lived-rg> --sku Standard --allocation-method Static --location <location>. Leave empty to allocate a fresh IP each apply (DNS must then be re-pointed after every rebuild)."
  type        = string
  default     = ""
}

variable "existing_public_ip_resource_group_name" {
  description = "Resource group holding the pre-created Public IP named by existing_public_ip_name. MUST be a different resource group from var.resource_group_name -- Terraform deletes its own resource group on destroy, which would take the IP with it and defeat the entire point. Ignored when existing_public_ip_name is empty."
  type        = string
  default     = ""
}

# ---------------------------------------------------------------------------
# Bootstrap payload
# ---------------------------------------------------------------------------

variable "github_repo_url" {
  description = "HTTPS URL of the repo to clone onto the VM during bootstrap. Defaults to the public graphwise-stack-builder repo. Override only if you've forked."
  type        = string
  default     = "https://github.com/kentstroker/graphwise-stack-builder.git"
}

variable "github_branch" {
  description = "Branch of github_repo_url that cloud-init clones onto the VM. Default \"main\" matches the canonical deploy path. Set to a feature branch when running destroy/apply to test in-flight chart changes that haven't merged yet."
  type        = string
  default     = "main"
}

variable "kind_version" {
  description = "KIND release pinned into the bootstrap. Do NOT bump past a node image whose containerd exceeds the host's -- KIND 0.32.0's node ships containerd 2.3.1 (config v4), which a 2.2.x host containerd can't read, breaking `kind load`. This is the single highest-risk difference on Azure: AL2023 bundles a containerd 2.2.x docker package, whereas Rocky/RHEL install Docker CE, whose containerd.io package version is NOT guaranteed to match. Smoke-test `kind load docker-image` on the first build before trusting the stack (see README.md -> Known risks)."
  type        = string
  default     = "v0.30.0"
}

variable "kubectl_version" {
  description = "kubectl release pinned into the bootstrap. Matches the KIND node image's Kubernetes version (v1.33.4) so `kubectl` and the API server never skew."
  type        = string
  default     = "v1.33.4"
}

variable "helm_version" {
  description = "Helm release pinned into the bootstrap."
  type        = string
  default     = "v3.17.0"
}

# ---------------------------------------------------------------------------
# Auto-shutdown (BEHAVIOUR DIFFERS FROM AWS -- read the description)
# ---------------------------------------------------------------------------

variable "auto_shutdown_enabled" {
  description = "Create an Azure auto-shutdown schedule that DEALLOCATES the VM daily at auto_shutdown_time. This is NOT a port of the AWS module's idle-CPU alarm -- Azure Monitor has no native VM-stop action, so idle-based shutdown would need a metric alert plus an action group plus an Automation runbook. This resource is TIME-based: it will deallocate the VM at the configured hour even if a demo is in progress. Set false on demo days, or accept the notification email and click 'postpone'. See README.md -> Auto-shutdown for the idle-based upgrade path."
  type        = bool
  default     = true
}

variable "auto_shutdown_time" {
  description = "Local time-of-day the auto-shutdown fires, as a 24h HHMM string with no colon (e.g. \"1900\" = 7pm). Interpreted in auto_shutdown_timezone."
  type        = string
  default     = "1900"

  validation {
    condition     = can(regex("^([01][0-9]|2[0-3])[0-5][0-9]$", var.auto_shutdown_time))
    error_message = "auto_shutdown_time must be a 4-digit 24h HHMM string with no colon (e.g. \"1900\")."
  }
}

variable "auto_shutdown_timezone" {
  description = "Windows timezone name (NOT an IANA name) that auto_shutdown_time is interpreted in -- Azure uses the Windows naming here even for Linux VMs. Examples: \"Pacific Standard Time\", \"Eastern Standard Time\", \"UTC\", \"W. Europe Standard Time\". Full list: az rest --method get --url 'https://management.azure.com/subscriptions/<sub>/providers/Microsoft.DevTestLab?api-version=2018-09-15' or the Windows tz database."
  type        = string
  default     = "Pacific Standard Time"
}

variable "auto_shutdown_notification_email" {
  description = "Email address that receives a 30-minute warning before the auto-shutdown deallocates the VM. The warning mail carries a 'postpone' link, which is the only mitigation for the time-based (rather than idle-based) shutdown behaviour -- strongly recommended. Leave empty to disable notifications entirely."
  type        = string
  default     = ""
}

# ---------------------------------------------------------------------------
# Naming + tags
# ---------------------------------------------------------------------------

variable "instance_name_prefix" {
  description = "Prefix for every Azure resource name and the Name tag. Final name is \"<prefix>-<subdomain-slug>-<role>\". Keep short -- Azure resource-name length limits are per-type and some are as low as 24 characters."
  type        = string
  default     = "graphwise-stack"
}

variable "creator" {
  description = "Name (or email) of the operator running this deployment. Surfaced as the Creator tag on every Azure resource -- shows up in Cost Management and Azure Policy so shared-subscription spend can be attributed and orphaned resources traced back to their owner. Required: an empty string fails validation to prevent unattributed deploys."
  type        = string

  validation {
    condition     = length(trimspace(var.creator)) > 0
    error_message = "creator must be set to a name or email so Azure resources are attributable. Add `creator = \"Your Name\"` to terraform.tfvars."
  }
}

variable "purpose" {
  description = "Short free-text label describing what this deployment is FOR (e.g. \"Chevron presales demo\", \"Azure port validation\"). Surfaced as the Purpose tag on every resource so later shared-subscription cleanup can tell live demos from forgotten test rigs."
  type        = string
  default     = "unspecified"
}

variable "extra_tags" {
  description = "Additional tags applied to every resource. Merged AFTER the module defaults, so an entry with the same key overrides the module value (escape hatch for orgs whose tagging policy expects, say, `Owner` instead of `Creator`)."
  type        = map(string)
  default     = {}
}
